export const styles = {
    chatButton: {
      position: "fixed",
      bottom: "20px",
      right: "20px",
      background: "#0078ff",
      color: "white",
      padding: "14px",
      borderRadius: "50%",
      border: "none",
      cursor: "pointer",
      fontSize: "22px",
      boxShadow: "0px 4px 10px rgba(0,0,0,0.2)",
    },
    chatContainer: {
      position: "fixed",
      bottom: "80px",
      right: "20px",
      width: "350px",
      height: "500px",
      borderRadius: "12px",
      background: "white",
      boxShadow: "0px 6px 12px rgba(0,0,0,0.15)",
      display: "flex",
      flexDirection: "column",
      overflow: "hidden",
    },
    chatHeader: {
      background: "#25D366",
      color: "white",
      padding: "12px",
      fontSize: "18px",
      fontWeight: "bold",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
    },
    messageList: {
      flex: 1,
      overflowY: "auto",
      padding: "10px",
      background: "#f9f9f9",
      display: "flex",
      flexDirection: "column",
    },
    message: (sender) => ({
      display: "flex",
      justifyContent: sender === "user" ? "flex-end" : "flex-start",
      marginBottom: "8px",
    }),
    messageBubble: (sender) => ({
      maxWidth: "70%",
      padding: "12px",
      borderRadius: "18px",
      background: sender === "user" ? "#0078ff" : "#e0e0e0",
      color: sender === "user" ? "white" : "black",
      wordWrap: "break-word",
      fontSize: "16px",
    }),
    inputContainer: {
      display: "flex",
      padding: "10px",
      borderTop: "1px solid #ddd",
      background: "white",
    },
    input: {
      flex: 1,
      padding: "12px",
      borderRadius: "20px",
      border: "1px solid #ccc",
      fontSize: "18px",
      outline: "none",
    },
    sendButton: {
      marginLeft: "10px",
      padding: "12px 18px",
      borderRadius: "20px",
      background: "#0078ff",
      color: "white",
      border: "none",
      cursor: "pointer",
      fontSize: "18px",
    },
  };